name: CarRental
options:
  bundleIdPrefix: ru.shiftlab
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    GENERATE_INFOPLIST_FILE: YES
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
targets:
  CarRental:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ru.shiftlab.carrental
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
  CarRentalTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: CarRental
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ru.shiftlab.carrental.tests
